### ISSUE TITLE
Doesn't work with gnome 3.22

### ISSUE THREAD

**Issue by martinm1000** [kgaut/gnome-shell-audio-output-switcher#12]
I see this error in the looking glass:

TypeError: this.construct is not a function

**Comment by luca-viggiani** [comment]
Did you mean 3.32?

**Comment by martinm1000** [comment]
@luca-viggiani Yes, sorry. But I'm using some other plugin that looks quite similar and works.
(https://extensions.gnome.org/extension/751/audio-output-switcher/)

**Comment by madscientist** [comment]
Yes, seeing the same after upgrading to Ubuntu 19.04 which is based on Gnome 3.22.  journalctl says:
```
May 18 14:16:52 homebase gnome-shell[2058]: Extension "gnome-shell-audio-output-switcher@kgaut" had error: TypeError: this._construct is not a function
May 18 14:16:52 homebase gnome-software[2734]: State change on user/*/*/shell-extension/gnome-shell-audio-output-switcher_kgaut/* from available to installed is not OK
May 18 14:16:52 homebase gnome-software[2734]: gnome-shell-audio-output-switcher_kgaut has error: TypeError: this._construct is not a function
```
